version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./envoy/front-envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "50051:50051"
      - "8001:8001"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'front-envoy' --service-node 'front-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  app1-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./envoy/app1-envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "50052:50052"
      - "8002:8002"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'app1-envoy' --service-node 'app1-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  app2-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./envoy/app2-envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "50053:50053"
      - "8003:8003"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'app2-envoy' --service-node 'app2-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  statsd-exporter:
    image: prom/statsd-exporter:latest
    ports:
    - "9125:9125"
    - "9102:9102"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus.yaml
    ports:
    - "9090:9090"
    command: "--config.file=/etc/prometheus.yaml"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    ports:
    - "3000:3000"
